import type { Database } from "./db/database.types";

// -----------------------------
// DTOs and Command Models
// -----------------------------

// 1. Flashcard DTO - corresponds to a record in the flashcards table
export type FlashcardDTO = Database["public"]["Tables"]["flashcards"]["Row"];

// 1a. FlashcardType - flashcard type stored in the database
// This is a database enum used in the "type" column of the flashcards table.
// Possible values: "manual", "ai-full" (AI without editing), "ai-edited" (AI with editing)
export type FlashcardType = Database["public"]["Enums"]["flashcard_type"];

// 2. CreateFlashcardCommand
// Input data for creating a flashcard (single or multiple).
// FlashcardSource is an alias for FlashcardType - we use the same values in API and database.
// Requirements:
//    - "manual" -> generation_id must be null
//    - "ai-full" -> generation_id is required (flashcard generated by AI without editing)
//    - "ai-edited" -> generation_id is required (flashcard generated by AI with editing)
// Limits for all flashcards:
//    - front: max 200 characters
//    - back: max 500 characters
export type FlashcardSource = FlashcardType;

export interface CreateFlashcardCommand {
  front: string; // required, front text (max 200 characters)
  back: string; // required, back text (max 500 characters)
  source: FlashcardSource; // specifies flashcard origin
  generation_id?: number; // required for "ai-full" and "ai-edited", null for "manual"
}

// 2a. BulkCreateFlashcardsCommand
// Command to create multiple flashcards at once (max 100).
// Used in POST /api/flashcards with body: { flashcards: [...] }
export interface BulkCreateFlashcardsCommand {
  flashcards: CreateFlashcardCommand[]; // array of flashcards (max 100 items)
}

// 2b. BulkCreateFlashcardsResponse
// Response from POST /api/flashcards endpoint for bulk create.
export interface BulkCreateFlashcardsResponse {
  count: number; // number of created flashcards
  flashcards: FlashcardDTO[]; // created flashcards in the same order as request
}

// 3. UpdateFlashcardCommand
// Enables partial flashcard update.
export interface UpdateFlashcardCommand {
  front?: string; // optionally, new front text
  back?: string; // optionally, new back text
}

// 4. BulkDeleteFlashcardsCommand
// Command to delete multiple flashcards at once.
export interface BulkDeleteFlashcardsCommand {
  flashcard_ids: number[]; // list of flashcard IDs to delete
}

// 5. GenerateFlashcardsCommand
// Command to generate flashcard proposals using AI.
// AI returns proposals (front, back) which are NOT yet saved in the database.
// User reviews proposals and approves them via POST /api/flashcards
// (single or bulk with CreateFlashcardCommand).
export interface GenerateFlashcardsCommand {
  source_text: string; // source text with length 1000-10000 characters
}

// 6. Generation DTO - corresponds to a record in the generations table
export type GenerationDTO = Database["public"]["Tables"]["generations"]["Row"];

// 7. GenerationError DTO - corresponds to a record in the generation_error_logs table
export type GenerationErrorDTO = Database["public"]["Tables"]["generation_error_logs"]["Row"];

// 8. Study Session DTO - corresponds to a record in the study_sessions table
export type StudySessionDTO = Database["public"]["Tables"]["study_sessions"]["Row"];

// 9. Session Flashcard DTO - corresponds to a record in the session_flashcards table
export type SessionFlashcardDTO = Database["public"]["Tables"]["session_flashcards"]["Row"];

// 10. CreateStudySessionCommand - input data to create a study session
export interface CreateStudySessionCommand {
  userId: string;
}

// 11. UpdateStudySessionCommand - update of basic session data
export interface UpdateStudySessionCommand {
  completedAt?: string;
  flashcardsCount?: number;
  averageRating?: number;
}

// 12. StartStudySessionResponse - result of starting a study session
export interface StartStudySessionResponse {
  studySession: StudySessionDTO;
  flashcards: FlashcardDTO[];
}

// 13. UpdateSessionFlashcardCommand - input data to rate a flashcard in a session
export interface UpdateSessionFlashcardCommand {
  studySessionId: number;
  flashcardId: number;
  lastRating: number;
}

// 14. GetStudyHistoryResponse - API response with session history
export interface GetStudyHistoryResponse {
  studySessions: StudySessionDTO[];
  pagination?: {
    page: number;
    limit: number;
    total: number;
    total_pages?: number;
  };
}

// 15. GetFlashcardsDueResponse - response with list of flashcards requiring review
export interface GetFlashcardsDueResponse {
  flashcards: (FlashcardDTO & {
    nextReviewAt: string;
    lastRating: number | null;
    reviewCount: number;
    stability: number;
    difficulty: number;
    lapses: number;
    state: number;
  })[];
}

// 16. UserStatisticsDTO
// Corresponds to the data structure from GET /api/users/me/statistics endpoint.
export interface UserStatisticsDTO {
  flashcards: {
    total: number;
    by_type: Record<FlashcardType, number>;
  };
  generations: {
    total_sessions: number;
    total_generated: number;
    total_accepted: number;
    acceptance_rate: number; // percentage value, e.g. 75
    edit_rate: number; // percentage value, e.g. 20
  };
}
