-- Migration: Create flashcards, generations, and generation_error_logs tables
-- Purpose: Initial database schema for 10x-cards application
-- Affected tables: flashcards, generations, generation_error_logs
-- Special considerations: Implements Row Level Security (RLS) for flashcards table
-- Created: 2025-10-29

-- ============================================================================
-- ENUM TYPES
-- ============================================================================

-- Create enum type for flashcard type
-- Defines the source/type of flashcard creation method
create type flashcard_type as enum ('ai-full', 'ai-edited', 'manual');

-- ============================================================================
-- TABLES
-- ============================================================================

-- Create generations table
-- Purpose: Store statistics and metadata for each AI generation operation
create table generations (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  generated_count integer not null default 0,
  accepted_unedited_count integer default 0,
  accepted_edited_count integer default 0,
  source_text_hash varchar(64) not null,
  source_text_length integer not null,
  generation_duration integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  
  -- Constraints to ensure valid counts when present
  constraint check_generated_count_positive check (generated_count >= 0),
  constraint check_accepted_unedited_positive check (accepted_unedited_count is null or accepted_unedited_count >= 0),
  constraint check_accepted_edited_positive check (accepted_edited_count is null or accepted_edited_count >= 0),
  constraint check_accepted_not_exceeding_generated check (
    accepted_unedited_count is null or accepted_edited_count is null or
    accepted_unedited_count + accepted_edited_count <= generated_count
  ),
  constraint check_source_text_length_positive check (source_text_length > 0),
  constraint check_generation_duration_positive check (generation_duration is null or generation_duration > 0)
);

-- Add comments to generations table
comment on table generations is 'Statistics and metadata for AI flashcard generation operations';
comment on column generations.user_id is 'Reference to the user who initiated the generation';
comment on column generations.generated_count is 'Total number of flashcards generated by AI in this operation';
comment on column generations.accepted_unedited_count is 'Number of flashcards accepted without any edits (type: ai-full). Updated after user reviews generated cards. Default 0.';
comment on column generations.accepted_edited_count is 'Number of flashcards accepted after editing (type: ai-edited). Updated after user reviews generated cards. Default 0.';
comment on column generations.source_text_hash is 'SHA256 hash of the source text for duplicate detection and caching';
comment on column generations.source_text_length is 'Length of source text in characters';
comment on column generations.generation_duration is 'Duration of AI generation process in milliseconds. Nullable if measurement failed.';

-- Create generation_error_logs table
-- Purpose: Store error logs for failed AI generation attempts
create table generation_error_logs (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_text_hash varchar(64) not null,
  source_text_length integer not null,
  error_code varchar(50) not null,
  error_message text not null,
  created_at timestamptz not null default now(),
  
  -- Constraint to ensure valid source text length
  constraint check_error_source_text_length_positive check (source_text_length > 0)
);

-- Add comments to generation_error_logs table
comment on table generation_error_logs is 'Error logs for failed AI generation attempts';
comment on column generation_error_logs.user_id is 'Reference to the user who attempted the generation';
comment on column generation_error_logs.source_text_hash is 'SHA256 hash of the source text that caused the error';
comment on column generation_error_logs.source_text_length is 'Length of source text in characters';
comment on column generation_error_logs.error_code is 'Error code (e.g., API_TIMEOUT, INVALID_RESPONSE, RATE_LIMIT)';
comment on column generation_error_logs.error_message is 'Detailed error message for debugging';

-- Create flashcards table
-- Purpose: Store user flashcards with support for manual and AI-generated content
create table flashcards (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  generation_id bigint references generations(id) on delete set null,
  type flashcard_type not null default 'manual',
  front text not null,
  back text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  
  -- Constraints for manual flashcards to enforce length limits
  constraint check_manual_front_length check (
    type != 'manual' or length(front) <= 200
  ),
  constraint check_manual_back_length check (
    type != 'manual' or length(back) <= 500
  ),
  -- Constraint to ensure AI-generated cards have a generation_id
  constraint check_ai_has_generation_id check (
    type = 'manual' or generation_id is not null
  )
);

-- Add comments to flashcards table
comment on table flashcards is 'User flashcards for spaced repetition learning';
comment on column flashcards.user_id is 'Reference to the owner of the flashcard';
comment on column flashcards.generation_id is 'Optional reference to generation record if card was AI-generated';
comment on column flashcards.type is 'Source of flashcard: ai-full (fully AI-generated), ai-edited (AI-generated but edited), manual (user-created)';
comment on column flashcards.front is 'Front side of flashcard (question/prompt), max 200 chars for manual cards';
comment on column flashcards.back is 'Back side of flashcard (answer), max 500 chars for manual cards';

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Indexes for flashcards table
create index idx_flashcards_user_id on flashcards(user_id);
comment on index idx_flashcards_user_id is 'Fast filtering of flashcards by user';

create index idx_flashcards_type on flashcards(type);
comment on index idx_flashcards_type is 'Fast filtering of flashcards by creation method';

create index idx_flashcards_generation_id on flashcards(generation_id);
comment on index idx_flashcards_generation_id is 'Fast lookup of flashcards from a specific generation';

create index idx_flashcards_created_at on flashcards(created_at);
comment on index idx_flashcards_created_at is 'Fast sorting and filtering by creation date';

create index idx_flashcards_updated_at on flashcards(updated_at);
comment on index idx_flashcards_updated_at is 'Fast sorting and filtering by last modification date';

-- Indexes for generations table
create index idx_generations_user_id on generations(user_id);
comment on index idx_generations_user_id is 'Fast filtering of generations by user';

create index idx_generations_source_text_hash on generations(source_text_hash);
comment on index idx_generations_source_text_hash is 'Fast lookup for duplicate detection and caching';

create index idx_generations_created_at on generations(created_at);
comment on index idx_generations_created_at is 'Fast sorting and analysis of generation history';

-- Indexes for generation_error_logs table
create index idx_error_logs_user_id on generation_error_logs(user_id);
comment on index idx_error_logs_user_id is 'Fast filtering of error logs by user';

create index idx_error_logs_error_code on generation_error_logs(error_code);
comment on index idx_error_logs_error_code is 'Fast analysis of error types and patterns';

create index idx_error_logs_created_at on generation_error_logs(created_at);
comment on index idx_error_logs_created_at is 'Fast sorting and analysis of error history';

-- ============================================================================
-- TRIGGER FUNCTIONS
-- ============================================================================

-- Function to automatically update updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

comment on function update_updated_at_column is 'Automatically updates the updated_at column to current timestamp';

-- Trigger to update updated_at on flashcards table
create trigger update_flashcards_updated_at
  before update on flashcards
  for each row
  execute function update_updated_at_column();

-- Trigger to update updated_at on generations table
create trigger update_generations_updated_at
  before update on generations
  for each row
  execute function update_updated_at_column();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Enable RLS on flashcards table
-- IMPORTANT: This ensures users can only access their own flashcards
alter table flashcards enable row level security;

-- ============================================================================
-- RLS POLICIES FOR FLASHCARDS TABLE
-- ============================================================================

-- Policy: Allow authenticated users to select their own flashcards
-- Rationale: Users should be able to view all their flashcards for study sessions
create policy "flashcards_select_authenticated"
  on flashcards
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Policy: Allow authenticated users to insert their own flashcards
-- Rationale: Users should be able to create new flashcards
create policy "flashcards_insert_authenticated"
  on flashcards
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to update their own flashcards
-- Rationale: Users should be able to edit their flashcards
create policy "flashcards_update_authenticated"
  on flashcards
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to delete their own flashcards
-- Rationale: Users should be able to remove unwanted flashcards
create policy "flashcards_delete_authenticated"
  on flashcards
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- Policy: Deny all access to anonymous users for select
-- Rationale: Flashcards are private user data, no public access
create policy "flashcards_select_anon_deny"
  on flashcards
  for select
  to anon
  using (false);

-- Policy: Deny all access to anonymous users for insert
-- Rationale: Anonymous users cannot create flashcards
create policy "flashcards_insert_anon_deny"
  on flashcards
  for insert
  to anon
  with check (false);

-- Policy: Deny all access to anonymous users for update
-- Rationale: Anonymous users cannot update flashcards
create policy "flashcards_update_anon_deny"
  on flashcards
  for update
  to anon
  using (false);

-- Policy: Deny all access to anonymous users for delete
-- Rationale: Anonymous users cannot delete flashcards
create policy "flashcards_delete_anon_deny"
  on flashcards
  for delete
  to anon
  using (false);

